// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbWajSvTndMrG6TC3TeJLwYmETSRuyn4',
    appId: '1:643787906551:web:9a7d4ce87fe596c5efe2f2',
    messagingSenderId: '643787906551',
    projectId: 'act15-b9da5',
    authDomain: 'act15-b9da5.firebaseapp.com',
    storageBucket: 'act15-b9da5.firebasestorage.app',
    measurementId: 'G-29LZG8110P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsEwRMpopD732GmZtpnMiS5lpvfoEeoYQ',
    appId: '1:643787906551:android:5e77f7c96033a8faefe2f2',
    messagingSenderId: '643787906551',
    projectId: 'act15-b9da5',
    storageBucket: 'act15-b9da5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsg2275uaaeEPYk0eLeTLJ9tj4KmyrX6E',
    appId: '1:643787906551:ios:dad074424ebdbfc6efe2f2',
    messagingSenderId: '643787906551',
    projectId: 'act15-b9da5',
    storageBucket: 'act15-b9da5.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsg2275uaaeEPYk0eLeTLJ9tj4KmyrX6E',
    appId: '1:643787906551:ios:dad074424ebdbfc6efe2f2',
    messagingSenderId: '643787906551',
    projectId: 'act15-b9da5',
    storageBucket: 'act15-b9da5.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApbWajSvTndMrG6TC3TeJLwYmETSRuyn4',
    appId: '1:643787906551:web:7f15ecfcdba27a43efe2f2',
    messagingSenderId: '643787906551',
    projectId: 'act15-b9da5',
    authDomain: 'act15-b9da5.firebaseapp.com',
    storageBucket: 'act15-b9da5.firebasestorage.app',
    measurementId: 'G-BS308FRPQX',
  );
}
